/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup-email` | `/signup-email`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup-interest` | `/signup-interest`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup-photos` | `/signup-photos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup-profile` | `/signup-profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup-submit` | `/signup-submit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup-gender` | `/signup-gender`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Home` | `/Home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup-email` | `/signup-email`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup-interest` | `/signup-interest`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup-photos` | `/signup-photos`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup-profile` | `/signup-profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup-submit` | `/signup-submit`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup-gender` | `/signup-gender`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Home` | `/Home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup-email${`?${string}` | `#${string}` | ''}` | `/signup-email${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup-interest${`?${string}` | `#${string}` | ''}` | `/signup-interest${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup-photos${`?${string}` | `#${string}` | ''}` | `/signup-photos${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup-profile${`?${string}` | `#${string}` | ''}` | `/signup-profile${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup-submit${`?${string}` | `#${string}` | ''}` | `/signup-submit${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup-gender${`?${string}` | `#${string}` | ''}` | `/signup-gender${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Home${`?${string}` | `#${string}` | ''}` | `/Home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Profile${`?${string}` | `#${string}` | ''}` | `/Profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup-email` | `/signup-email`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup-interest` | `/signup-interest`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup-photos` | `/signup-photos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup-profile` | `/signup-profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup-submit` | `/signup-submit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup-gender` | `/signup-gender`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Home` | `/Home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownInputParams; };
    }
  }
}
